// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Mv8PL4LU5VB3BAjAB9_siN1hQvC37Rw',
    appId: '1:214968875672:web:718d722e276df274dc2eed',
    messagingSenderId: '214968875672',
    projectId: 'my-sport-tracker',
    authDomain: 'my-sport-tracker.firebaseapp.com',
    storageBucket: 'my-sport-tracker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31Dxi4uop5ifdxJhhHfDUUR1f_QaMB4E',
    appId: '1:214968875672:android:5d7e3140e7a2dcacdc2eed',
    messagingSenderId: '214968875672',
    projectId: 'my-sport-tracker',
    storageBucket: 'my-sport-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgO7aCS-JbcXB09RoyevG8qJBg2JqAOA',
    appId: '1:214968875672:ios:47fa7bc62ba1449ddc2eed',
    messagingSenderId: '214968875672',
    projectId: 'my-sport-tracker',
    storageBucket: 'my-sport-tracker.appspot.com',
    iosBundleId: 'Mikhail_22alt.sportTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVgO7aCS-JbcXB09RoyevG8qJBg2JqAOA',
    appId: '1:214968875672:ios:47fa7bc62ba1449ddc2eed',
    messagingSenderId: '214968875672',
    projectId: 'my-sport-tracker',
    storageBucket: 'my-sport-tracker.appspot.com',
    iosBundleId: 'Mikhail_22alt.sportTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Mv8PL4LU5VB3BAjAB9_siN1hQvC37Rw',
    appId: '1:214968875672:web:4a14c109a8f3ee05dc2eed',
    messagingSenderId: '214968875672',
    projectId: 'my-sport-tracker',
    authDomain: 'my-sport-tracker.firebaseapp.com',
    storageBucket: 'my-sport-tracker.appspot.com',
  );
}
